device: cpu #cpu  0
epochs: 20
early_stop_steps: 20

trainer:
  max_grad_norm: 1
  reg_weight_decay: 0.001
  reg_norm: 1
data:
  batch-size: 256
  dataset: multi_data/Anki #nomaskmomo #duolingo_kan/all_data
loss:
  name: MaskedMAELoss

optimizer:
  name: Adam
  Adam:
    lr: 0.0005
    weight_decay: 0.00001
    amsgrad: true
  RMSprop:
    lr: 0.0005
    weight_decay: 0.0001

optimizer_sr:
  name: Adam
  Adam:
    lr: 0.001
    weight_decay: 0.0001
    amsgrad: true
  RMSprop:
    lr: 0.0001
    weight_decay: 0.0001


scheduler:
  name: CosineAnnealingLR
  ReduceLROnPlateau:
    factor: 0.2
    patience: 5
    threshold: 0.003
    min_lr: 0.00001
  StepLR:
    step_size: 10
    gamma: 0.1
  MultiStepLR:
    milestones: [2, 10, 20, 50]
    gamma: 0.3
  CosineAnnealingLR:
    T_max: 5
    eta_min: 0.0000001

model:
  MyRKan:
    widthRKAN: [9,3] # momo [8,3]  duolingo [10,3] Anki [9,3]
    widthsolute : [4,3]
    resultKan: [3,1]
  KAN:
    width:  [6,3,3,1]  #[6,3,3,1]   # momo[5,3,1] duolingo[7,3,1]
  DKT:
    n_question: 50000
    p_num: 150000
    embed_l: 100
    embed_p: 64
    input_dim: 7
    hidden_dim: 32
    layer_num: 1
    output_dim: 1
  Transformer:
    n_question: 12326
    p_num: 20962
    embed_l: 100
    embed_p: 64
    i_vocab_size: 175
    t_vocab_size: 175
    odeflag: Flase
  FIFAKT:
    n_question: 150000
    p_num: 150000
    embed_l: 100
    embed_p: 64
    hidden_dim: 50
    input_size: 11
  DNN:
    hidden_dim: 256
  LogisticRegression:
    num_labels: 1
    num_features: 8
  RNN:
    n_question: 12326
    p_num: 20962
    embed_l: 100
    embed_p: 64
    input_dim: 11
    hidden_dim: 256
    layer_num: 1
    output_dim: 1
  SAKT:
    ex_total: 12326
    seq_len: 16
    dim: 256
    heads: 2
    dout: 0
  QIKTNet:
    num_q: 12326
    num_c: 12326
    emb_size: 256
  SimpleKT:
    n_question: 12326
    n_pid: 1
    d_model: 256
    n_blocks: 2
    dropout: 0.3
  MIKT:
    skill_max: 100
    pro_max: 100
    embed: 64
    p: 0
  Linear:
    input_dim: 3



